import cv2
import numpy as np

img = cv2.imread('screenshot.png',0)
ret, img = cv2.threshold(img,250,255,cv2.THRESH_BINARY_INV)
cv2.imwrite('original.png',img)
kernel=cv2.getStructuringElement(cv2.MORPH_RECT,(1,3))
erosion = cv2.erode(img,kernel)
cv2.imwrite('short_ver.png',erosion)
kernel=cv2.getStructuringElement(cv2.MORPH_RECT,(1,5))
erosion = cv2.erode(img,kernel)
cv2.imwrite('normal_ver.png',erosion)
kernel=cv2.getStructuringElement(cv2.MORPH_RECT,(1,15))
erosion = cv2.erode(img,kernel)
cv2.imwrite('long_ver.png',erosion)
kernel=cv2.getStructuringElement(cv2.MORPH_RECT,(3,1))
erosion = cv2.erode(img,kernel)
cv2.imwrite('short_hor.png',erosion)
kernel=cv2.getStructuringElement(cv2.MORPH_RECT,(5,1))
erosion = cv2.erode(img,kernel)
cv2.imwrite('normal_hor.png',erosion)
kernel=cv2.getStructuringElement(cv2.MORPH_RECT,(15,1))
erosion = cv2.erode(img,kernel)
cv2.imwrite('long_hor.png',erosion)
